spring:
  application:
    name: logistics
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
server:
  error:
    include-message: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
logistics:
  transport:
    delay:
      limit:
        first-category: 0
        second-category: 30
        third-category: 60
        fourth-category: 120
      percentage:
        first-category: 2
        second-category: 4
        third-category: 8
        fourth-category: 16
