spring:
  application:
    name: logistics
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
